server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8186/realms/spring-microservices-security-realm

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/order/**

        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/inventory/**
